pub const FRIEND_INFO_HEADER: &str = r#"
# Friend information, generated by a really early version of frauth.
#
# This file is not intended to be edited by hand.
"#;

pub const USER_INFO_HEADER: &str = r#"
# User information, generated by a really early version of frauth.
#
# THIS FILE CONTAINS SECRET DATA! You should never post or share it anywhere!
#
# Instead, use command `frauth publish` to generate the file to publish publicly.
#
# This file is not intended to be edited by hand.
"#;

pub const PEER_INFO_HEADER: &str = r#"
# Peer information, generated by a really early version of frauth.
#
# This file is not intended to be edited by hand.
"#;
